### ISSUE TITLE
用不明白

### ISSUE THREAD

**Issue by Asleeplover** [TwoOnefour/Sign_xy#3]
用不明白，登录不上啊

**Comment by TwoOnefour** [comment]
武理的请用门户登陆，华师的不保证能登陆

Asleeplover ***@***.***> 於 2024年3月15日週五 下午10:14寫道：

**Comment by Asleeplover** [comment]
Traceback (most recent call last):
  File "D:\edge下载\Sign_xy-sign_xy-v2.0\Sign_xy-sign_xy-v2.0\main.py", line 29, in <module>
    mybot.run()
  File "D:\edge下载\Sign_xy-sign_xy-v2.0\Sign_xy-sign_xy-v2.0\__init__.py", line 367, in run
    if self.login():
       ^^^^^^^^^^^^
  File "D:\edge下载\Sign_xy-sign_xy-v2.0\Sign_xy-sign_xy-v2.0\__init__.py", line 135, in login
    url = self.whut_login(
          ^^^^^^^^^^^^^^^^
  File "D:\edge下载\Sign_xy-sign_xy-v2.0\Sign_xy-sign_xy-v2.0\__init__.py", line 77, in whut_login
    public_key = self.sessions.post("http://zhlgd.whut.edu.cn/tpass/rsa").json()["publicKey"]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86181\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] HTTP method GET is not supported by this URL: 0

**Comment by TwoOnefour** [comment]
我尝试一下，稍等

Asleeplover ***@***.***> 於 2024年3月16日週六 下午3:18寫道：

**Comment by TwoOnefour** [comment]
可以登陆的，不要下载release版本，那个我还没更新，请直接git clone使用

twoonefour ***@***.***> 於 2024年3月16日週六 下午3:24寫道：

**Comment by TwoOnefour** [comment]
现release已更新，谢谢提醒

twoonefour ***@***.***> 於 2024年3月16日週六 下午3:26寫道：
